### PR TITLE
fix: unable to connect ledger nano S on Ubuntu

### PR DESCRIPTION
**Pull request by jaeseung-bae**
## Description

closes: #1039
* The latest version for `github.com/cosmos/ledger-cosmos-go` is `v0.13.0`. The latest version breaks some interfaces so I bump up with `v0.12.2`(the second latest one) which is enough to fix the issue.

## Motivation and context

* #1039 

## How has this been tested?

* I tested with a nano S plus ledger on both Ubuntu 20.04 and Mac

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/finschia-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/finschia-sdk/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Review by zemyblue — COMMENTED** [review]
I think this PR is duplicated with #1027 .
The #1027 PR bumps up ledger-cosmos-go to v0.13.0

What shall we do in order to use ledger-cosmos-go v0.13.0?

**Comment by jaeseung-bae** [comment]
> os-go v0.13.0

From v0.13.0, interface SECP256K1's SignSECP256K1 function has changed. 
`v0.13.0` introduces `feat!: Add SIGN_MODE_TEXTUAL`
In order to use `v0.13.0`, some of code that use `SignSECP256K1()`, must be changed for compile.

```go
SECP256K1 interface {
		SignSECP256K1([]uint32, []byte) ([]byte, error) // v0.12.2
		SignSECP256K1([]uint32, []byte, byte) ([]byte, error) // v0.13.0
}
```

**Comment by jaeseung-bae** [comment]
Do you think It is better to change the code to adapt v0.13.0 from PR #1027

**Comment by zemyblue** [comment]
> @zemyblue, Do you think It is better to change the code to adapt v0.13.0 from PR #1027.

Yes, but I think we cannot use v0.13.0 in this case. 
I want to know why v0.13.0 can't.

**Review by zemyblue — APPROVED** [review]

**Review by loin3 — APPROVED** [review]

**Pull request merged**
