### PR TITLE
fix: update swap keys for possibly overlapped keys

### PR DESCRIPTION
**Pull request by jaeseung-bae**
## Description

* fix: update swap keys for possibly overlapped keys
  * They should be the same -> `(hello, world)` != `(hell, oworld)`

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/finschia-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/finschia-sdk/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [x] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Review by 0Tech — COMMENTED** [review]
We should prohibit denoms longer than 255.

**Comment by jaeseung-bae** [comment]
> We should prohibit denoms longer than 255.

Can i have any reason for 255 limit?

**Comment by 0Tech** [comment]
> > We should prohibit denoms longer than 255.
> 
> Can i have any reason for 255 limit?

It's because our newly introduced lengthPrefix() assumes it (converts int to byte).

**Comment by jaeseung-bae** [comment]
> > > We should prohibit denoms longer than 255.
> > 
> > 
> > Can i have any reason for 255 limit?
> 
> It's because our newly introduced lengthPrefix() assumes it (converts int to byte).

Thanks for letting me know.

I found regex for denom validation `[a-zA-Z][a-zA-Z0-9/-]{2,127}`.
function to get key will be called after `validation logic`, so it's okay without length limit.

**Review by zemyblue — APPROVED** [review]

**Comment by jaeseung-bae** [comment]
> > > > We should prohibit denoms longer than 255.
> > > 
> > > 
> > > Can i have any reason for 255 limit?
> > 
> > 
> > It's because our newly introduced lengthPrefix() assumes it (converts int to byte).
> 
> Thanks for letting me know.
> 
> I found regex for denom validation `[a-zA-Z][a-zA-Z0-9/-]{2,127}`. function to get key will be called after `validation logic`, so it's okay without length limit.

I got another case to call without `validation logic`.
I've just made commit to fix it.

**Review by 0Tech — APPROVED** [review]

**Review by zemyblue — APPROVED** [review]

**Pull request merged**
