### PR TITLE
chore: Bump up Ostracon to 1.1.1

### PR DESCRIPTION
**Pull request by tnasu**
## Description

Bump up Ostracon to v1.1.1
See: 
* CHANGELOG: https://github.com/Finschia/ostracon/blob/main/CHANGELOG.md#v111
* TAG: https://github.com/Finschia/ostracon/releases/tag/v1.1.1
* PR: https://github.com/Finschia/ostracon/pull/679

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/finschia-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/finschia-sdk/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Review by zemyblue — APPROVED** [review]

**Comment by ulbqb** [comment]
Aren't there modified stub files?

**Comment by tnasu** [comment]
@ulbqb Thanks, but, what are `stub files`?

**Review by torao — APPROVED** [review]

**Comment by ulbqb** [comment]
@tnasu
Stub files are `*.pb.go` files. Are there any changes in these files?

**Review by jaeseung-bae — APPROVED** [review]

**Comment by zemyblue** [comment]
> @tnasu
> Stub files are `*.pb.go` files. Are there any changes in these files?

The stub files of third_party is not used in fisnchia-sdk. The files in the third_party are just referred for compile.

**Comment by zemyblue** [comment]
Sorry, closed by mistake.

**Review by ulbqb — APPROVED** [review]

**Pull request merged**
