### PR TITLE
docs: Update script

### PR DESCRIPTION
**Pull request by shiki-tak**
## Description

I split the test script.

## Checklist:

- [ ] I followed the [contributing guidelines](https://github.com/Finschia/finschia-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/finschia-sdk/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Comment by Mdaiki0730** [comment]
The GOPATH may be different if you are using a version management tool, etc., so would you use the host's GOPATH without defining it in the shell file?

**Review by Mdaiki0730 — APPROVED** [review]
LGTM

**Review by zemyblue — COMMENTED** [review]
Please use appropriate prefix like `feat` or `chore` or `docs` etc in title.

**Comment by ulbqb** [comment]
Can you replace demo/L1/simd-darwin-arm64 with a docker image?

**Comment by shiki-tak** [comment]
> Can you replace simd-darwin-arm64 with a docker image?

In this PR, I only want to update the script, so I will deal with it in a separate issue.

**Review by ulbqb — APPROVED** [review]

**Pull request merged**
