### PR TITLE
fix: correctly coalesce coins even with repeated denominations(backport cosmos/cosmos-sdk#13265)

### PR DESCRIPTION
**Pull request by jaeseung-bae**
## Description

* (audit issue) correctly coalesce coins even with repeated denominations
  * backport cosmos/cosmos-sdk#13265

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/finschia-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/finschia-sdk/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Comment by Mdaiki0730** [comment]
Please resolve the conflict.

**Review by 170210 — DISMISSED** [review]

**Comment by Mdaiki0730** [comment]
It looks like the cla signature is missing. Could you please sign it?

**Comment by jaeseung-bae** [comment]
> It looks like the cla signature is missing. Could you please sign it?

I've signed CLA. I think it's because of cherry-pick from upstream.
Please ignore it.

**Comment by Mdaiki0730** [comment]
> I've signed CLA. I think it's because of cherry-pick from upstream.
> Please ignore it.

Won't ignoring it block the merge?
Since cherry-pick has made it co-author, how about making only @jaeseung-bae 's commit?

**Comment by jaeseung-bae** [comment]
> > I've signed CLA. I think it's because of cherry-pick from upstream.
> > Please ignore it.
> 
> Won't ignoring it block the merge? Since cherry-pick has made it co-author, how about making only @jaeseung-bae 's commit?

I was able to merge without sign from co-author.
I'll try to leave my commit only.

**Review by Mdaiki0730 — APPROVED** [review]

**Review by 0Tech — APPROVED** [review]

**Pull request merged**
