### PR TITLE
fix: update param validation to fail on nil dec

### PR DESCRIPTION
**Pull request by jaeseung-bae**
## Description

* fix: update param validation to fail on nil dec
  * refer: https://github.com/cosmos/cosmos-sdk/pull/13553

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/finschia-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/finschia-sdk/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Review by 0Tech — DISMISSED** [review]

**Comment by 170210** [comment]
Is it necessary to add the same contents under x/distribution? There are three similar bugs under x/distribution.

**Comment by jaeseung-bae** [comment]
> Is it necessary to add the same contents under x/distribution? There are three similar bugs under x/distribution.

I can't find any in x/distribution, could you share the points?

**Comment by 170210** [comment]
> I can't find any in x/distribution, could you share the points?

https://github.com/Finschia/finschia-sdk/blob/main/x/distribution/types/params.go#L76-L131

**Comment by 170210** [comment]
> I can't find any in x/distribution, could you share the points?
Sorry, I made a mistake. There's no problem under x/distribution...

**Review by 170210 — APPROVED** [review]

**Review by zemyblue — APPROVED** [review]

**Pull request merged**
